name: test_prep_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get:
  dio: ^5.8.0+1
  intl: ^0.20.2
  hive: ^2.2.3
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  readmore: ^3.0.0
  hive_flutter: ^1.1.0
  dismissible_page: ^1.0.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.0
  flutter_tabler_icons: ^1.43.0
  # flutter_cache_manager: ^3.4.1
  # http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
